# Generated by Django 4.2.10 on 2024-02-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_menu_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
