# Generated by Django 5.0.2 on 2024-02-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_food_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activity_level',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='biological_sex',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='weight_in_grams',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.CreateModel(
            name='FoodEnergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cal_per_100g', models.IntegerField(default=1, null=True)),
                ('prot_per_100g', models.IntegerField(default=1, null=True)),
                ('fat_per_100g', models.IntegerField(default=1, null=True)),
                ('carbs_per_100g', models.IntegerField(default=1, null=True)),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.food')),
            ],
        ),
    ]
