# Generated by Django 5.0.2 on 2024-04-12 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cafe", "0002_order_transaction_id"),
        ("cafe", "0003_food_category"),
    ]

    operations = []
