# Generated by Django 5.0.2 on 2024-02-27 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_customer_activity_level_customer_biological_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodenergy',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='energy',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.foodenergy'),
        ),
    ]
