# Generated by Django 5.0.2 on 2024-02-28 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_order_transaction_id'),
        ('cafe', '0005_remove_foodenergy_food_food_energy'),
    ]

    operations = [
    ]
