# Generated by Django 4.2.10 on 2024-06-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_merge_20240228_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='weight_in_grams',
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
